### ISSUE TITLE
failed status line parse leads to missing resp parts

### ISSUE THREAD

**Issue by jdv** [skaji/perl6-HTTP-Tinyish#5]
I would suggest not silently skipping the header handling if the status line can't be parsed.
I would throw hard so that its clear what happened.  I found this when I hit a server that
kicked a status line of "HTTP/2 200".  Here's a fix:

https://gist.github.com/anonymous/71057da9cacf1e5a9c2b74ba84af761b

You might want to expose the http version so it can be tested better.

**Comment by skaji** [comment]
Could you give me a PR?
